/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fvitali' at '1/3/17 10:04 AM' with Gradle 3.2.1
 *
 * @author fvitali, @date 1/3/17 10:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
